#!/usr/bin/env python3

import runpy
import subprocess
import sys
import tkinter as tk
from tkinter import messagebox


def show_error_dialog(title, message):
    root = tk.Tk()
    root.withdraw()  # Hide the main window
    messagebox.showerror(title, message)
    root.destroy()


import os
import platform
import shutil

system = platform.system()

def find_slack_executable():
    if system == "Windows":
        possible_folders = [
            os.path.expandvars(r"%LOCALAPPDATA%\slack"),
            os.path.expandvars(r"%PROGRAMFILES%\slack"),
            os.path.expandvars(r"%PROGRAMFILES(X86)%\slack")
        ]
        for folder in possible_folders:
            if os.path.isdir(folder):
                for f in reversed(sorted(os.listdir(folder))):
                    if f.startswith("app-"):
                        return [folder, os.path.join(folder, f, "slack.exe")]

    elif system == "Darwin":  # macOS
        slack_path = shutil.which("Slack")
        if slack_path:
            return slack_path
        default_path = "/Applications/Slack.app/Contents/MacOS/Slack"
        if os.path.isfile(default_path):
            return default_path

    elif system == "Linux":
        slack_path = shutil.which("slack")
        if slack_path:
            return slack_path

        possible_paths = [
            "/usr/bin/slack",
            "/usr/local/bin/slack",
            "/snap/bin/slack"
        ]
        for path in possible_paths:
            if os.path.isfile(path):
                return path

    return None

slack_path = find_slack_executable()

if getattr(sys, 'frozen', False):
    # If running as a PyInstaller bundle
    base_path = sys._MEIPASS
else:
    # If running in a normal Python environment
    base_path = os.path.dirname(__file__)

if slack_path:
    try:
        if system == "Windows":
            print(f"Slack executable found at: {slack_path[1]}")
            sys.argv = ["electron_inject", "-r", os.path.join(base_path, 'slack-when-ready.js'), "-t", "120", "-",
                        os.join(slack_path[0], "Update.exe"), "--processStart", slack_path[1]]
        else:
            print(f"Slack executable found at: {slack_path}")
            sys.argv = ["electron_inject", "-r", os.path.join(base_path, 'slack-when-ready.js'), "-t", "120", "-", slack_path]
        runpy.run_module("electron_inject", run_name="__main__", alter_sys=True)
    except Exception as e:
        print(f"An error occurred: {e}")
        input("Press Enter to exit...")
else:
    show_error_dialog("Error", "Slack executable not found.")

